Lab7: main.o
	g++ -g -std=c++11 main.o -o Lab7

main.o: main.cpp BubbleSort.h BubbleSort.hpp MergeSort.h MergeSort.hpp BogoSort.h BogoSort.hpp InsertionSort.h InsertionSort.hpp QuickSort.h QuickSort.hpp Sort.h Sort.hpp
	g++ -g -std=c++11 -c main.cpp

clean: 
	rm *.o Lab7
